version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hubdb
      POSTGRES_USER: hub
      POSTGRES_PASSWORD: hubpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data: